### ISSUE TITLE
`darvaza serve`'s Run mix up in Config{}

### ISSUE THREAD

**Issue by amery** [darvaza-proxy/darvaza#1]
Hi, I think this should be moved out of Config{} and run directly on serve's Run()

@karasz thoughts?

https://github.com/darvaza-proxy/darvaza/blob/47dc1b731b86558ca1ce8aaefb13e85a88b9e38a/cmd/darvaza/config.go#L29

**Comment by amery** [comment]
as part of the same, this usage of the `wg` violates some boundaries.
https://github.com/darvaza-proxy/darvaza/blob/47dc1b731b86558ca1ce8aaefb13e85a88b9e38a/cmd/darvaza/server.go#L35

**Comment by karasz** [comment]
Regarding the `RunProxies()` you are right, it feels indeed a bit out of place on Config{}, I'll think about moving it that should also fix the `wg` thing. 

Thanks for noticing it.
